### ISSUE TITLE
Automatic IP detection with docker ps

### ISSUE THREAD

**Issue by nowNick** [u2i/rspec-hive#20]
Today I've run to an issue where I've been connecting to wrong IP on docker. I had 2 docker-machines running and the default one was not accepting any connection. However there is a possiblity to check all running docker machines and to show user which one you are using so such an issue like this might be discovered earlier. We show it right now when we run config but we don't show which machines are running. I think we could detect if user is trying to connect to a local docker machine on a wrong IP. What do you guys think? @wmiel  @mknapik

**Comment by mknapik** [comment]
I don't think we're able to cover all possibilities.
E.g. I'm using native Docker for OSX (closed beta) so I had to reconfigure `rspec-hive.yml`.

**Comment by wmiel** [comment]
@mknapik Is configuration simpler with native docker? I think we can slowly move in this direction, I don't think they'll want to stick with the VirtualBox solution for much longer.

**Comment by mknapik** [comment]
It's nearly the same. Host changes and `docker-machine` becomes obsolete.
It's still beta though.
