### ISSUE TITLE
Publish gem in Rubygems and fix its name.

### ISSUE THREAD

**Issue by wmiel** [u2i/rspec-hive#6]
It's used in Gemfile as "hive_tests" which does not correspond to the repo name. 
It could also be published in rubygems to make it easier to use.

**Comment by nowNick** [comment]
Good idea. Im gonna look at it.

**Comment by nowNick** [comment]
What name should we choose? "hive_tests" or "ns-rspec-hive" ?

**Comment by wmiel** [comment]
Awesome, I think ns-rspec-hive or u2i-rspec_hive would more or less follow Mr. Knapik's convention, what do you think?

**Comment by nowNick** [comment]
I would stick with:
http://guides.rubygems.org/name-your-gem/
Maybe just: "rspec_hive" ? It will be under u2i organisation so maybe we won't need it in name. As I analyze these guides I think including u2i in name could be troublesome. Is that ok?

**Comment by wmiel** [comment]
sure

**Comment by piotrlezon** [comment]
fyi, I added u2i rubygems account to teampassword as I wanted to push ns_settings_ui too (which also has the problem of the shitty name :()

**Comment by mknapik** [comment]
:+1: For publishing this Gem.
@nowNick provided a good guidelines on naming gems.
I was thinking about `u2i-rspec_hive`. `U2i` module kind of promotes u2i and allows to avoid conflicts.
On the other hand, if you look at rspec gems the pattern is `rspec-sth`, e.g.
* rspec-core
* rspec-mocks
* rspec-rails

So how about renaming modules and naming the gem `rspec-hive` to match those convention?
@wmiel @piotrlezon

**Comment by wmiel** [comment]
@mknapik I'm good with changing it.

**Comment by piotrlezon** [comment]
:+1:

**Comment by nowNick** [comment]
Should we change the namespace of rake tasks along with this gem name change? Right now the most outer namespace is `hive_tests`.

**Comment by wmiel** [comment]
@nowNick I think so, I would make it consistent with the Gem's name.

**Comment by nowNick** [comment]
So the outer namespace should be `rspec-hive` or `hive` I am not sure if `rspec-hive` is permitted. And what about docker image? Right now it is `nielsensocial/hive`

**Comment by nowNick** [comment]
Maybe `rspec:hive: <tasks here>` for rake tasks and `rspec/hive` for docker image name?

**Comment by nowNick** [comment]
This has been fixed in #7

**Comment by nowNick** [comment]
I have published it to RubyGems.
https://rubygems.org/gems/rspec-hive

**Comment by mknapik** [comment]
@nowNick Good job!
